---
- name: Create Directories
  ansible.builtin.file:
    path: "/{{ ansible_facts['user_dir'] }}/{{ item }}"
    state: directory
    mode: 0755
  loop:
    - .ssh
    - .config
    - .config/ghostty

- name: Set Editor Symlinks
  ansible.builtin.file:
    src: "/{{ ansible_facts['user_dir'] }}/Projects/dotfiles/roles/alpha/files/{{ item }}"
    dest: "/{{ ansible_facts['user_dir'] }}/{{ item }}"
    state: link
    force: true
  loop:
    - .emacs.d

- name: Set Dotfiles Symlinks
  ansible.builtin.file:
    src: "/{{ ansible_facts['user_dir'] }}/Projects/dotfiles/roles/alpha/files/{{ item }}"
    dest: "/{{ ansible_facts['user_dir'] }}/{{ item }}"
    state: link
    force: true
  loop:
    - .zprofile
    - .zshrc
  notify: event_reload_zsh_files
