---
- name: Set Editor Symlink (EMACS PLUS)
  ansible.builtin.file:
    src: "/{{ ansible_facts['user_dir'] }}/Projects/dotfiles/roles/beta/files/emacs-plus"
    dest: "/{{ ansible_facts['user_dir'] }}/.config/emacs-plus"
    state: link
    force: true
  notify:
    - event_reload_zsh_files

- name: Set Ghostty Symlink
  ansible.builtin.file:
    src: "/{{ ansible_facts['user_dir'] }}/Projects/dotfiles/roles/beta/files/ghostty/macos"
    dest: "/{{ ansible_facts['user_dir'] }}/.config/ghostty/config"
    state: link
    force: true

- name: Set Dotfiles Symlinks
  ansible.builtin.file:
    src: "/{{ ansible_facts['user_dir'] }}/Projects/dotfiles/roles/beta/files/{{ item }}"
    dest: "/{{ ansible_facts['user_dir'] }}/{{ item }}"
    state: link
    force: true
  loop:
    - .beta_profile
  notify: event_reload_zsh_files
