---
- name: Create Configuration Directory
  ansible.builtin.file:
    path: "/{{ ansible_facts['user_dir'] }}/.config"
    state: directory
    mode: 0755

- name: Set Editor Symlinks
  ansible.builtin.file:
    src: "/{{ ansible_facts['user_dir'] }}/Projects/dotfiles/roles/common/files/{{ item }}"
    dest: "/{{ ansible_facts['user_dir'] }}/.config/{{ item }}"
    state: link
    force: true
  loop:
    - nvim
    - doom

- name: Set Dotfiles Symlinks
  ansible.builtin.file:
    src: "/{{ ansible_facts['user_dir'] }}/Projects/dotfiles/roles/common/files/{{ item }}"
    dest: "/{{ ansible_facts['user_dir'] }}/{{ item }}"
    state: link
    force: true
  loop:
    - .commonrc
    - .common_profile
    - .zprofile
    - .zshrc
    - .private_profile
  notify: event_reload_zsh_files

- name: Create SSH Directory
  ansible.builtin.file:
    path: "/{{ ansible_facts['user_dir'] }}/.ssh"
    state: directory
    mode: 0755

- name: Create Ghostty Directory
  ansible.builtin.file:
    path: "/{{ ansible_facts['user_dir'] }}/.config/ghostty"
    state: directory
    mode: 0755
