---
- name: Set Ghostty Symlink
  ansible.builtin.file:
    src: "/{{ ansible_facts['user_dir'] }}/.dotfiles/files/ghostty/macos"
    dest: "/{{ ansible_facts['user_dir'] }}/.config/ghostty/config"
    state: link
    force: true

