---
- name: Set SSH Symlink
  command: >
    ln -s -f
    "/{{ ansible_facts['user_dir'] }}/Akeptous/dotfiles/systems/macos/ssh/config"
    "/{{ ansible_facts['user_dir'] }}/.ssh/config"
  args:
    chdir: "/{{ ansible_facts['user_dir'] }}/Akeptous/dotfiles/systems/macos"
    creates: "/{{ ansible_facts['user_dir'] }}/.ssh/config"
  notify: 
    - "event_reload_zsh_files"

- name: Set Editor Symlink (EMACS PLUS)
  command: >
    ln -s -f
    "{{ ansible_facts['user_dir'] }}/Akeptous/dotfiles/systems/macos/emacs-plus"
    "{{ ansible_facts['user_dir'] }}/.config/emacs-plus"
  args:
    chdir: "/{{ ansible_facts['user_dir'] }}/Akeptous/dotfiles/systems/macos"
    creates: "/{{ ansible_facts['user_dir'] }}/.config/emacs-plus/build.yml"
  notify: 
    - "event_reload_zsh_files"
