---
- name: Set SSH Symlink
  ansible.builtin.file:
    src: "/{{ ansible_facts['user_dir'] }}/Projects/dotfiles/roles/macos/files/ssh/config"
    dest: "/{{ ansible_facts['user_dir'] }}/.ssh/config"
    state: link
    force: true
  notify:
    - "event_reload_zsh_files"

- name: Set Editor Symlink (EMACS PLUS)
  ansible.builtin.file:
    src: "/{{ ansible_facts['user_dir'] }}/Projects/dotfiles/roles/macos/files/emacs-plus"
    dest: "/{{ ansible_facts['user_dir'] }}/.config/emacs-plus"
    state: link
    force: true
  notify:
    - "event_reload_zsh_files"
