---
- name: Set Ghostty Symlink
  ansible.builtin.file:
    src: "/{{ ansible_facts['user_dir'] }}/Projects/dotfiles/roles/common/files/ghostty/linux"
    dest: "/{{ ansible_facts['user_dir'] }}/.config/ghostty/config"
    state: link
    force: true
