---
- name: Enable Repositories On Brew
  community.general.homebrew_tap:
    name: "{{ item }}"
    state: present
  loop:
    - clojure-lsp/brew
    - coursier/formulas

- name: Install Dependencies
  community.general.homebrew:
    name:
      - coursier
      - clojure-lsp-native
    state: latest
  notify:
    - event_install_npm_dependencies
