---
- name: Set Work Symlink
  ansible.builtin.file:
    src: "/{{ ansible_facts['user_dir'] }}/.dotfiles/files/{{ item }}"
    dest: "/{{ ansible_facts['user_dir'] }}/{{ item }}"
    state: link
    force: true
  loop:
    - .work_profile
  notify: event_reload_zsh_files
