---
- name: Create Directories
  ansible.builtin.file:
    path: "/{{ ansible_facts['user_dir'] }}/{{ item }}"
    state: directory
    mode: 0755
  loop:
    - .ssh
    - .config
    - .config/ghostty

- name: Set Editor Symlink
  ansible.builtin.file:
    src: "/{{ ansible_facts['user_dir'] }}/.dotfiles/files/{{ item }}"
    dest: "/{{ ansible_facts['user_dir'] }}/.config/{{ item }}"
    state: link
    force: true
  loop:
    - nvim
  notify: event_reload_zsh_files

- name: Set Symlinks
  ansible.builtin.file:
    src: "/{{ ansible_facts['user_dir'] }}/.dotfiles/files/{{ item }}"
    dest: "/{{ ansible_facts['user_dir'] }}/{{ item }}"
    state: link
    force: true
  loop:
    - .zprofile
    - .zshrc
  notify: event_reload_zsh_files
