$ANSIBLE_VAULT;1.1;AES256
30333163373431653161333838363761306639313838636161663135363833313364303264303661
3039353531636265303663623233323562316361376631370a313936306664636631306163623562
65653138383731613663646362646663613465633665313335663539623430383930376439646563
6535313136303462380a343361383537386564376330626538663739393539383732643238373130
30666639656638356537636264343236653137663231386633363263363539366266653061643662
62653832613030303231346430363438393165633461363038353839353939373431336130663335
37393930636237323761313266623535323636613039613039323838356266326562306331346238
37626335633230633232353466626561343833366632623963366635613333313365663938366636
37613836356162643238363131393431343832386164373762373562636565326230623963616565
32396437353831383037303265346464313965643235666539653765663064633139363232376461
32303862316638303231396465333633313733346632373931366262346435643265343564356334
64323037643837323431326337653763643630313331646234326564376563663262306434303231
35356466376539613130396363343332323964646664623764636266333237636332373135613933
30383234356665666135616362363534383533663235323666343331306236626532656630353332
30363363626135346437613339356561306437356233303334316462356131383762303061386231
35316632386336633733396534653563386439373062613362323831636661336332646136376330
32656431333239663633393462343565666463656639363561346238353162326337653630633831
63326137366365343736396135326337616261383333663661653665616331383861323732656537
62333534656261313239373662303239656336666465663035613139353039633763323032376636
39343564333635333735
