$ANSIBLE_VAULT;1.1;AES256
62373366623366653664363932613539333434303435613833653934643131616437336561623962
3361663036623530333932316366383764633535393962630a333436336261653861366536323234
35656433623462373833346138376161653565666537336166633936643634646235656663363464
6439636438396363620a643133306538663038363631626461623761643733376231343439633766
38616530343035383330393438363532393962396635643765333433353435333033616630333737
64643032343236616330393566396233646262353731666265326262373930336137396538313337
66326639353436343339643634613938393862326162376339623639346330353332336634396538
64303331326466353961646134623165303335336639313561626464326662373066636365663865
63613231386364313461663932653363373663326533666461376235376430653266363239363937
62376665336533343631663336376232303635336330636161336163306666366232306137366664
64356530613235316439386433346636373063653839363065656531326637393936663134336632
66303233646236646462663564396364363463643438316130323662636662633438386438396637
30343336623337616562353962336536333434633463396139393231306364363364636436333738
62356236383130343463393866363561636134353032333363333137333462313939353566336361
63353433393266336461383434346431663431636538393835333032646132393965633432396130
38373436623466626464316136383338666165336564363364326431313738386365623738353037
30326533633833646166336465633030643633386238313534646133633763666162643636343633
64343366366538666563656262346535636630393338646162376465366532623162363730376232
63613163343537653731666430356361343261396337313032356531326538346263313531663664
62343235383231643030
