---
- name: Add SSH Key To Agent (Linux)
  shell: |
    eval "$(ssh-agent -s)"
    ssh-add "{{ ansible_facts['user_dir'] }}/.ssh/{{ ansible_facts['user_id'] }}_rsa"
  when:
    - "'ansible-generated' not in ssh_keys_added.stdout"

